# Generated by Django 4.2.7 on 2023-11-11 04:49

import bookapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=36, unique=True)),
                ("description", models.TextField(blank=True, max_length=256)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("published", models.DateField()),
                ("is_published", models.BooleanField(default=False)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to=bookapp.models.upload_image
                    ),
                ),
            ],
        ),
    ]
