# Generated by Django 4.2.7 on 2023-11-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn_10", models.CharField(blank=True, max_length=10)),
                ("isbn_13", models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="number",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookapp.booknumber",
            ),
        ),
    ]
