# Generated by Django 4.2.7 on 2023-11-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0003_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character",
                to="bookapp.book",
            ),
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=30)),
                (
                    "books",
                    models.ManyToManyField(related_name="author", to="bookapp.book"),
                ),
            ],
        ),
    ]
